project_recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500


handler404 = 'recipe.views.custom_404'
handler500 = 'recipe.views.custom_500'


urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("recipe.urls"), name="recipe-urls"),
]

recipe/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path(
        '',
        views.RecipeList.as_view(),
        name='home'
    ),
    path(
        '<slug:slug>/',
        views.recipe_feature,
        name='recipe_feature'
     ),
    path(
        '<slug:slug>/edit_comment/<int:comment_id>',
        views.comment_edit,
        name='comment_edit'
     ),
    path(
        '<slug:slug>/delete_comment/<int:comment_id>',
        views.comment_delete,
        name='comment_delete'
     ),
]

recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))
RATING_CHOICES = [
        (0, '0'),
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]


class Recipe(models.Model):
    """Recipe model"""
    title = models.CharField(
        max_length=300, unique=True, blank=False, null=False
    )
    slug = models.SlugField(max_length=300, unique=True)
    image = CloudinaryField('image', default='placeholder')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipe_uploads"
    )
    serves = models.PositiveIntegerField(blank=False, null=False)
    ingredients = models.TextField(max_length=900, blank=False, null=False)
    method = models.TextField(max_length=3000, blank=False, null=False)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(max_length=900, blank=False, null=False)


class Comment(models.Model):
    """Comment model"""
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter"
    )
    body = models.TextField(
        "Max characters 900", max_length=900, blank=False, null=False
    )
    rating = models.IntegerField(choices=RATING_CHOICES, default=0)
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

recipe/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    """Comment Form"""
    class Meta:
        model = Comment
        fields = ('body',)

recipe/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Recipe, Comment
from .forms import CommentForm


class RecipeList(generic.ListView):
    """Recipe List View"""
    model = Recipe
    template_name = "recipe/index.html"
    paginate_by = 3


def recipe_feature(request, slug):
    """
    Display an individual recipe:model:`recipe.Recipe`.

    **Context**

    ``recipe``
        An instance of :model:`recipe.Recipe`.

    **Template:**

    :template:`recipe/recipe_feature.html`
    """

    queryset = Recipe.objects.filter(status=1)
    recipe = get_object_or_404(queryset, slug=slug)
    comments = recipe.comments.all().order_by("-created_on")

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.recipe = recipe
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error submitting comment!')

    comment_form = CommentForm()

    return render(
        request,
        "recipe/recipe_feature.html",
        {"recipe": recipe,
         "comments": comments,
         "comment_form": comment_form,
         },
    )


def comment_edit(request, slug, comment_id):
    """
    Edit a comment from user :model:`recipe.Comment`.

    **Context**

    ``recipe``
        An instance of :model:`recipe.Recipe`.
    ``comment``
        An instance of :model:`recipe.Comment`.

    **Template:**

    :template:`recipe/recipe_feature.html`
    """
    if request.method == "POST":

        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('recipe_feature', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    Delete a comment from user :model:`recipe.Comment`.

    **Context**

    ``recipe``
        An instance of :model:`recipe.Recipe`.
    ``comment``
        An instance of :model:`recipe.Comment`.

    **Template:**

    :template:`recipe/recipe_feature.html`
    """
    queryset = Recipe.objects.filter(status=1)
    recipe = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('recipe_feature', args=[slug]))


def custom_404(request, exception):
    return render(request, '404.html', status=404)


def custom_500(request):
    return render(request, '500.html', status=500)

recipe/templates/recipe/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Display recipes -->
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 mt-3 left">
                <div class="row">
                    {% for recipe in recipe_list %}
                    <div class="col-md-4">
                        <a href="{% url 'recipe_feature' recipe.slug %}" class="hover" aria-label="Link to recipe feature">
                            <div class="card mb-4">
                                <div class="card-body">
                                    <h2 class="card-title text-center">{{ recipe.title }}</h2>
                                    <hr>
                                    <p>{{ recipe.excerpt }}</p>
                                    <hr>
                                    <div class="image-container image-list">
                                        {% if "placeholder" in recipe.image.url %}
                                        <img class="card-img-top" src="{% static 'images/default.jpeg' %}"
                                            alt="placeholder image">
                                        {% else %}
                                        <img class="card-img-top" src=" {{ recipe.image.url }}"
                                            alt="{{ recipe.title }} image">
                                        {% endif %}
                                        <hr>
                                    </div>
                                    <div class="image-flash">
                                        <p class="text-center">Serves: {{ recipe.serves }}</p>
                                        <p class="author text-center">Recipe by {{ recipe.author }}</p>
                                    </div>

                                </div>
                            </div>
                        </a>
                    </div>
                    {% if forloop.counter|divisibleby:3 %}
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<!-- Pagination and 'next'/'prev' buttons -->
<section aria-label="Page navigation">
    {% if is_paginated %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link button-style" aria-label="Link to preivous page">&laquo; PREV</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link button-style" aria-label="Link to next page"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
</section>
{% endif %}
{% endblock %}

recipe/templates/recipe/recipe_feature.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Display title, author, serves, excerpt and image for recipe -->
<section aria-label="Display recipe title, author, servings, excerpt and image">
  <div class="masthead">
    <div class="container mt-3">
      <div class="row g-0">
        <div class="col-md-6 masthead-text text-center">
          <h1 class="mt-5">{{ recipe.title }}</h1>
          <p>Recipe by {{ recipe.author }} | Serves {{ recipe.serves }}</p>
          <div class="mt-8 pr-4">
            <p><span class="quotes text-start"><i class="fa-solid fa-quote-left"></i></span>{{ recipe.excerpt }}<span
                class="quotes"><i class="fa-solid fa-quote-right"></i></span></p>
          </div>
        </div>
        <div class="d-none d-md-block col-md-6 masthead-image image-prop">
          {% if "placeholder" in recipe.image.url %}
          <img class="card-img-top" src="{% static 'images/default.jpeg' %}" alt="placeholder image">
          {% else %}
          <img class="card-img-top" src=" {{ recipe.image.url }}" alt="{{ recipe.title }}">
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Display ingredients and method for recipe -->
<section aria-label="Dispay ingredients and method for recipe">
  <div class="container mt-3">
    <div class="row">
      <div class="col-md-4 card mr-2 base-color">
        <h2 class="text-center mt-3">Ingredients</h2>
        <p>{{ recipe.ingredients | safe }}
      </div>
      <div class="col-md-8">
        <h2 class="text-center mt-3">Method</h2>
        <p>{{ recipe.method | safe }}
      </div>
    </div>
  </div>
</section>
<hr>
<!-- Display Comments -->
<section aria-label="Display comments">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h3 class="text-center">Comments</h3>
      <div class="card card-body">
        {% if comments|length == 0 %}
        <p>No comments left. Please leave a comment in the comment form</p>
        {% elif comments.approved == false %}
        <p>There are comments awaiting approval, before being shown to all users</p>
        {% endif %}
        {% for comment in comments %}
        <div class="card p-2 comments card-body
          {% if not comment.approved and comment.author == user %}
          faded{% elif not comment.approved %} d-none{% endif %}">
          <p class="font-weight-bold sm-italic">
            {{ comment.author }}
            wrote:
          </p>
          <div id="comment{{ comment.id }}">
            {{ comment.body | linebreaks }}
          </div>
          <div class="sm-italic">
            {{ comment.created_on }}
            {% if user.is_authenticated and comment.author == user %}
            <button class="btn edit-button button-style ml-5" data-comment-id="{{ comment.id }}" aria-label="Button to edit comment written by user">Edit</button>
            <button class="btn delete-button button-style delete" data-comment-id="{{ comment.id }}" aria-label="Button to delete users comment">Delete</button>
            {% endif %}
          </div>
          <div class="row text-end ml-6">
            {% if not comment.approved and comment.author == user %}
            <p class="approval sm-italic">
              This comment is awaiting approval
            </p>
            {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>
<hr>
<!-- Creating New Comments -->
<section aria-label="leave a comment form">  
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 mb-4 ml-3 mr-3 mt-3">
      {% if user.is_authenticated %}
      <h4 class="text-center">Leave a comment, from {{ user.username }}:</h4>
      <div class="">
        <form id="comment-form" method="post" class="card card-body">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" id="submit-update" class="btn btn-signup btn-lg button-style" data-bs-toggle="modal"
            data-bs-target="#commentModal" aria-label="Button to submit comment. Changes to update comment when comment has been edited">Submit</button>
        </form>
        {% else %}
        <p>Please <span><a href="{% url 'account_login' %}" aria-label="Link to login page">log in</a></span> to leave a comment</p>
        {% endif %}
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</section>
<!-- Delete confirmation modal -->
<aside class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content mod-sty">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close button"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary button-style" data-bs-dismiss="modal" aria-label="Close delete modal. Comment is not deleted and user is returned to page">Close</button>
        <a id="deleteConfirm" class="btn button-style delete" aria-label="Confirm delete comment. Comment is deleted and user is returned to page">Delete</a>
      </div>
    </div>
  </div>
</aside>

{% endblock content %}

{% block js %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}

templates/base.html
{% load static %}

{% url 'home' as home_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--Meta tags for search engines-->
  <meta name="description"
    content="A selection of cooking recipes are shown to try at home, with users able to comment">
  <meta name="keywords" content="cooking, recipes, food, home-cooking, kitchen, cook">
  <meta name="author" content="Lee Copeman">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
  </script>
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!--Favicon-->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static  'favicon/favicon-16x16.png' %}">
  <!--Title-->
  <title>{% block title %}Recipes At Home{% endblock %}</title>
</head>

<body>
  <!--Header-->
  <header>
    <nav class="navbar navbar-expand-sm base-color">
      <div class="container-fluid">
        <button class="navbar-toggler hover" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-end" id="navbarNav">
          <ul class="navbar-nav text-start">
            <li class="nav-item">
              <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page" aria-label="Link to home page"
                href="{% url 'home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page" aria-label="Link to logout page"
                href="{% url 'account_logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page" aria-label="Link to regiester page"
                href="{% url 'account_signup' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page" aria-label="Link to login page"
                href="{% url 'account_login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
        <a class="navbar-brand text-end" aria-label="Link to home page" href="{% url 'home' %}"><span class="capital">R</span>ecipes<span
            class="capital">@</span><br><span class="capital">H</span>ome</a>
      </div>
    </nav>
  </header>
  <!-- Display messages -->
  <aside aria-label="Display messages to user">
    <div class="container">
      <div class="row">
        <div class="col-8">
          {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible fade show message" id="msg" role="alert">
            {{ message | safe }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close message"></button>
          </div>
          {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <div class="col-4 text-end">
          <p>Signed in as {{ user }}</p>
        </div>
        {% endif %}
      </div>
    </div>
  </aside>

  <main>
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
  </main>

  <!-- Footer -->
  <footer class="bottom base-color">
    <div class="container">
      <div class="row py-4">
        <div class="col-md-4">
          <h5 class="text-center">About</h5>
          <p class="italic">Browse a diverse selection of recipes, giving you ideas you can try at home. </p>
        </div>
        <div class="col-md-4">
          <h5 class="text-center">Social Links</h5>
          <div class="social">
            <ul>
              <li>
                <a href="https://www.facebook.com" target="_blank" rel="noopener"
                  aria-label="Visit our Facebook page (opens in new tab)" class="hover"><i class="fa-brands fa-facebook"></i>-Facebook</a>
              </li>
              <li>
                <a href="https://twitter.com/" target="_blank" rel="noopener"
                  aria-label="Visit our Twitter page (opens in new tab)" class="hover"><i class="fa-brands fa-x-twitter"></i>-X</a>
              </li>
              <li>
                <a href="https://www.instagram.com/" target="_blank" rel="noopener"
                  aria-label="Visit our Instagram page (opens in new tab)" class="hover"><i class="fa-brands fa-instagram"></i>-Instagram</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4 text-center">
          <h5>&copy; 2024 Lee Copeman<br><a href="https://github.com/l-copeman" target="_blank" rel="noopener"
              aria-label="Visit Lee Copeman's GitHub Page (opens in new window)" class="hover"><i
                class="fa-brands fa-github mt-2"></i></a>
          </h5>
        </div>
      </div>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
    integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous">
  </script>

  <!-- Font Awesome -->
  <script rel="preconnect" src="https://kit.fontawesome.com/cd1fc6e5ef.js" crossorigin="anonymous"></script>
  <!-- JavaScript -->
  {% block js %}
  
  {% endblock %}
</body>

</html>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}